"""add business settings to users

Revision ID: 1c6d90148e41
Revises: b7bbab625916
Create Date: 2026-06-12 04:56:46.888891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6d90148e41'
down_revision: Union[str, Sequence[str], None] = 'b7bbab625916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with server_default so existing rows get sensible values, then drop
    # the default so the application-level defaults take over for new rows.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_goal', sa.Float(), nullable=False, server_default='10000'))
        batch_op.add_column(sa.Column('daily_capacity', sa.Integer(), nullable=False, server_default='20'))
        batch_op.add_column(sa.Column('client_term_singular', sa.String(), nullable=False, server_default='Cliente'))
        batch_op.add_column(sa.Column('client_term_plural', sa.String(), nullable=False, server_default='Clientes'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_goal', server_default=None)
        batch_op.alter_column('daily_capacity', server_default=None)
        batch_op.alter_column('client_term_singular', server_default=None)
        batch_op.alter_column('client_term_plural', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('client_term_plural')
        batch_op.drop_column('client_term_singular')
        batch_op.drop_column('daily_capacity')
        batch_op.drop_column('monthly_goal')

    # ### end Alembic commands ###
