"""add professional user_id login link

Revision ID: 42e72eb1be71
Revises: 62d954c83a05
Create Date: 2026-06-13 10:19:36.234679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e72eb1be71'
down_revision: Union[str, Sequence[str], None] = '62d954c83a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_professionals_user_id', ['user_id'])
        batch_op.create_foreign_key(
            'fk_professionals_user_id', 'users', ['user_id'], ['id']
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_professionals_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_professionals_user_id', type_='unique')
        batch_op.drop_column('user_id')
