"""add booking slug to users

Revision ID: 710ef06e30ea
Revises: 03ef56f9af6f
Create Date: 2026-06-11 01:08:10.833029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710ef06e30ea'
down_revision: Union[str, Sequence[str], None] = '03ef56f9af6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_slug', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_booking_slug'), ['booking_slug'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_booking_slug'))
        batch_op.drop_column('booking_slug')

    # ### end Alembic commands ###
