"""add professionals and scope schedule to professional

Revision ID: 72a0c096c425
Revises: 710ef06e30ea
Create Date: 2026-06-11 09:47:40.723119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a0c096c425'
down_revision: Union[str, Sequence[str], None] = '710ef06e30ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professionals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professionals_id'), ['id'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_appointments_professional_id', 'professionals', ['professional_id'], ['id'])

    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professional_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_working_hours_owner_weekday'), type_='unique')
        batch_op.create_unique_constraint('uq_working_hours_professional_weekday', ['professional_id', 'weekday'])
        batch_op.create_foreign_key('fk_working_hours_professional_id', 'professionals', ['professional_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('uq_working_hours_professional_weekday', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_working_hours_owner_weekday'), ['owner_id', 'weekday'])
        batch_op.create_foreign_key('fk_working_hours_owner_id', 'users', ['owner_id'], ['id'])
        batch_op.drop_column('professional_id')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('professional_id')

    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professionals_id'))

    op.drop_table('professionals')
    # ### end Alembic commands ###
