"""remove packages

Revision ID: 9ffe2276a77e
Revises: 1c6d90148e41
Create Date: 2026-06-12 21:02:27.543761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ffe2276a77e'
down_revision: Union[str, Sequence[str], None] = '1c6d90148e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop the appointments FK/column first so the referenced tables can be
    # removed safely on databases that enforce foreign keys.
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_client_package_id'), type_='foreignkey')
        batch_op.drop_column('client_package_id')

    with op.batch_alter_table('client_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_packages_id'))

    op.drop_table('client_packages')

    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_id'))

    op.drop_table('packages')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_package_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_client_package_id'), 'client_packages', ['client_package_id'], ['id'])

    op.create_table('packages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_id'), ['id'], unique=False)

    op.create_table('client_packages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('package_id', sa.INTEGER(), nullable=False),
    sa.Column('total_sessions', sa.INTEGER(), nullable=False),
    sa.Column('remaining_sessions', sa.INTEGER(), nullable=False),
    sa.Column('purchased_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_packages_id'), ['id'], unique=False)

    # ### end Alembic commands ###
