"""add appointment public_token and status

Revision ID: b7319b471ff4
Revises: 72a0c096c425
Create Date: 2026-06-11 10:07:13.765414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7319b471ff4'
down_revision: Union[str, Sequence[str], None] = '72a0c096c425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=False))
        batch_op.create_index(batch_op.f('ix_appointments_public_token'), ['public_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_public_token'))
        batch_op.drop_column('status')
        batch_op.drop_column('public_token')

    # ### end Alembic commands ###
