"""add created_at to clients

Revision ID: b7bbab625916
Revises: 3fa0495a41b3
Create Date: 2026-06-12 04:48:30.299710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7bbab625916'
down_revision: Union[str, Sequence[str], None] = '3fa0495a41b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Backfill existing rows with the current timestamp so the NOT NULL
    # constraint holds, then drop the server default for new inserts.
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'created_at',
                sa.DateTime(),
                nullable=False,
                server_default=sa.func.now(),
            )
        )

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('created_at', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
