"""add client consent and notification log

Revision ID: c081621e1b62
Revises: 1b7835087f2b
Create Date: 2026-06-14 21:32:17.575599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c081621e1b62'
down_revision: Union[str, Sequence[str], None] = '1b7835087f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_id'), ['id'], unique=False)

    # existing clients keep consent (opt-out model); drop the default after
    # backfilling so new rows rely on the application default.
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_consent', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('consent_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('notification_consent', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('consent_at')
        batch_op.drop_column('notification_consent')

    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_id'))

    op.drop_table('notification_logs')
    # ### end Alembic commands ###
